spring.application.name=backend
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://ep-wispy-resonance-av5zhe42.c-11.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_E4OiUQn0JkNV
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Upload limits for videos/assignments (optional but useful)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Razorpay Configuration
razorpay.key.id=rzp_test_TDFkDaRyYCXFH7
razorpay.key.secret=RDisG4npqrIH9pGRSHFbgNj5
